In [26]:
import pandas as pd
import zipfile
import os

In [27]:
os.getcwd()

'C:\\Users\\monika'

In [28]:
os.listdir()

['.android',
 '.AndroidStudio2.2',
 '.AndroidStudio2.3',
 '.AndroidStudio3.1',
 '.AndroidStudioPreview3.0',
 '.gradle',
 '.ipynb_checkpoints',
 '.ipython',
 '.jupyter',
 '.python_history',
 '3D Objects',
 'Amazon_Cleaned.csv',
 'Amazon_Cleaned.xlsx',
 'Amazon_Cleaned_1.csv',
 'Amazon_data_cleaning.ipynb',
 'AndroidStudioProjects',
 'AppData',
 'Application Data',
 'Blinkit_Cleaned.ipynb',
 'Blinkit_Dataset',
 'bootcamp1.ipynb',
 'Contacts',
 'Cookies',
 'customers_clean.csv',
 'delivery_clean.csv',
 'Documents',
 'Downloads',
 'Favorites',
 'feedback_clean.csv',
 'HR_ANALYTICS-CLEAR.ipynb',
 'HR_Analytics_Cleaned.csv',
 'HR_Analytics_Final.csv',
 'inventoryNew_clean.csv',
 'inventory_clean.csv',
 'learning python basic .ipynb',
 'Links',
 'Local Settings',
 'marketing_clean.csv',
 'Music',
 'My Documents',
 'NetHood',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{53b39e87-18c4-11ea-a811-000d3aa4692b}.TxR.0.regtrans-ms',
 'NTUSER.DAT{53b39e87-18c4-11ea-a811-000d3aa4692b}.TxR.1.regtrans-ms',
 'NTUSER.DAT{53b39e87-18c4-11ea-a811-000d3aa4692b}.TxR.2.regtrans-ms',
 'NTUSER.DAT{53b39e87-18c4-11ea-a811-000d3aa4692b}.TxR.blf',
 'NTUSER.DAT{53b39e88-18c4-11ea-a811-000d3aa4692b}.TM.blf',
 'NTUSER.DAT{53b39e88-18c4-11ea-a811-000d3aa4692b}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{53b39e88-18c4-11ea-a811-000d3aa4692b}.TMContainer00000000000000000002.regtrans-ms',
 'ntuser.ini',
 'OneDrive',
 'orders_clean.csv',
 'order_items_clean.csv',
 'PrintHood',
 'products.xml',
 'products_clean.csv',
 'Recent',
 'Saved Games',
 'Searches',
 'SendTo',
 'sonal_trial.ipynb',
 'Start Menu',
 'Templates',
 'Tracing',
 'Untitled.ipynb',
 'Videos']

In [29]:
with zipfile.ZipFile(r"C:\Users\monika\Downloads\archive(3).zip") as zip_ref:
    zip_ref.extractall("Blinkit_Dataset")

In [30]:
os.listdir("Blinkit_Dataset")

['blinkit_customers.csv',
 'blinkit_customer_feedback.csv',
 'blinkit_delivery_performance.csv',
 'blinkit_inventory.csv',
 'blinkit_inventoryNew.csv',
 'blinkit_marketing_performance.csv',
 'blinkit_orders.csv',
 'blinkit_order_items.csv',
 'blinkit_products.csv',
 'Category_Icons.xlsx',
 'Rating_Icon.xlsx']

In [31]:
products = pd.read_csv("Blinkit_Dataset/blinkit_products.csv")

orders = pd.read_csv("Blinkit_Dataset/blinkit_orders.csv")

order_items = pd.read_csv("Blinkit_Dataset/blinkit_order_items.csv")

customers = pd.read_csv("Blinkit_Dataset/blinkit_customers.csv")

feedback = pd.read_csv("Blinkit_Dataset/blinkit_customer_feedback.csv")

marketing = pd.read_csv("Blinkit_Dataset/blinkit_marketing_performance.csv")

inventory = pd.read_csv("Blinkit_Dataset/blinkit_inventory.csv")

inventory_new = pd.read_csv("Blinkit_Dataset/blinkit_inventoryNew.csv")

delivery = pd.read_csv("Blinkit_Dataset/blinkit_delivery_performance.csv")

In [32]:
print(products.shape)
print(orders.shape)
print(order_items.shape)
print(customers.shape)
print(feedback.shape)
print(marketing.shape)
print(inventory.shape)
print(inventory_new.shape)
print(delivery.shape)

(268, 10)
(5000, 10)
(5000, 4)
(2500, 11)
(5000, 8)
(5400, 11)
(75172, 4)
(18105, 4)
(5000, 8)

In [33]:
products.info()
orders.info()
order_items.info()
customers.info()
feedback.info()
marketing.info()
inventory.info()
inventory_new.info()
delivery.info()

<class 'pandas.DataFrame'>
RangeIndex: 268 entries, 0 to 267
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   product_id         268 non-null    int64
 1   product_name       268 non-null    str
 2   category           268 non-null    str
 3   brand              268 non-null    str
 4   price              268 non-null    float64
 5   mrp                268 non-null    float64
 6   margin_percentage  268 non-null    float64
 7   shelf_life_days    268 non-null    int64
 8   min_stock_level    268 non-null    int64
 9   max_stock_level    268 non-null    int64
dtypes: float64(3), int64(4), str(3)
memory usage: 21.1 KB
<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   order_id                5000 non-null   int64
 1   customer_id             5000 non-null   int64
 2   order_date              5000 non-null   str
 3   promised_delivery_time  5000 non-null   str
 4   actual_delivery_time    5000 non-null   str
 5   delivery_status         5000 non-null   str
 6   order_total             5000 non-null   float64
 7   payment_method          5000 non-null   str
 8   delivery_partner_id     5000 non-null   int64
 9   store_id                5000 non-null   int64
dtypes: float64(1), int64(4), str(5)
memory usage: 390.8 KB
<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   order_id    5000 non-null   int64
 1   product_id  5000 non-null   int64
 2   quantity    5000 non-null   int64
 3   unit_price  5000 non-null   float64
dtypes: float64(1), int64(3)
memory usage: 156.4 KB
<class 'pandas.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        2500 non-null   int64
 1   customer_name      2500 non-null   str
 2   email              2500 non-null   str
 3   phone              2500 non-null   int64
 4   address            2500 non-null   str
 5   area               2500 non-null   str
 6   pincode            2500 non-null   int64
 7   registration_date  2500 non-null   str
 8   customer_segment   2500 non-null   str
 9   total_orders       2500 non-null   int64
 10  avg_order_value    2500 non-null   float64
dtypes: float64(1), int64(4), str(6)
memory usage: 215.0 KB
<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   feedback_id        5000 non-null   int64
 1   order_id           5000 non-null   int64
 2   customer_id        5000 non-null   int64
 3   rating             5000 non-null   int64
 4   feedback_text      5000 non-null   str
 5   feedback_category  5000 non-null   str
 6   sentiment          5000 non-null   str
 7   feedback_date      5000 non-null   str
dtypes: int64(4), str(4)
memory usage: 312.6 KB
<class 'pandas.DataFrame'>
RangeIndex: 5400 entries, 0 to 5399
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   campaign_id        5400 non-null   int64
 1   campaign_name      5400 non-null   str
 2   date               5400 non-null   str
 3   target_audience    5400 non-null   str
 4   channel            5400 non-null   str
 5   impressions        5400 non-null   int64
 6   clicks             5400 non-null   int64
 7   conversions        5400 non-null   int64
 8   spend              5400 non-null   float64
 9   revenue_generated  5400 non-null   float64
 10  roas               5400 non-null   float64
dtypes: float64(3), int64(4), str(4)
memory usage: 464.2 KB
<class 'pandas.DataFrame'>
RangeIndex: 75172 entries, 0 to 75171
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   product_id      75172 non-null  int64
 1   date            75172 non-null  str
 2   stock_received  75172 non-null  int64
 3   damaged_stock   75172 non-null  int64
dtypes: int64(3), str(1)
memory usage: 2.3 MB
<class 'pandas.DataFrame'>
RangeIndex: 18105 entries, 0 to 18104
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   product_id      18105 non-null  int64
 1   date            18105 non-null  str
 2   stock_received  18105 non-null  int64
 3   damaged_stock   18105 non-null  int64
dtypes: int64(3), str(1)
memory usage: 565.9 KB
<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   order_id               5000 non-null   int64
 1   delivery_partner_id    5000 non-null   int64
 2   promised_time          5000 non-null   str
 3   actual_time            5000 non-null   str
 4   delivery_time_minutes  5000 non-null   float64
 5   distance_km            5000 non-null   float64
 6   delivery_status        5000 non-null   str
 7   reasons_if_delayed     3098 non-null   str
dtypes: float64(2), int64(2), str(4)
memory usage: 312.6 KB

In [34]:
print(products.isnull().sum())

print(orders.isnull().sum())

print(order_items.isnull().sum())

print(customers.isnull().sum())

print(feedback.isnull().sum())

print(marketing.isnull().sum())

print(inventory.isnull().sum())

print(inventory_new.isnull().sum())

print(delivery.isnull().sum())

product_id           0
product_name         0
category             0
brand                0
price                0
mrp                  0
margin_percentage    0
shelf_life_days      0
min_stock_level      0
max_stock_level      0
dtype: int64
order_id                  0
customer_id               0
order_date                0
promised_delivery_time    0
actual_delivery_time      0
delivery_status           0
order_total               0
payment_method            0
delivery_partner_id       0
store_id                  0
dtype: int64
order_id      0
product_id    0
quantity      0
unit_price    0
dtype: int64
customer_id          0
customer_name        0
email                0
phone                0
address              0
area                 0
pincode              0
registration_date    0
customer_segment     0
total_orders         0
avg_order_value      0
dtype: int64
feedback_id          0
order_id             0
customer_id          0
rating               0
feedback_text        0
feedback_category    0
sentiment            0
feedback_date        0
dtype: int64
campaign_id          0
campaign_name        0
date                 0
target_audience      0
channel              0
impressions          0
clicks               0
conversions          0
spend                0
revenue_generated    0
roas                 0
dtype: int64
product_id        0
date              0
stock_received    0
damaged_stock     0
dtype: int64
product_id        0
date              0
stock_received    0
damaged_stock     0
dtype: int64
order_id                    0
delivery_partner_id         0
promised_time               0
actual_time                 0
delivery_time_minutes       0
distance_km                 0
delivery_status             0
reasons_if_delayed       1902
dtype: int64

In [35]:
print(products.duplicated().sum())

print(orders.duplicated().sum())

print(order_items.duplicated().sum())

print(customers.duplicated().sum())

print(feedback.duplicated().sum())

print(marketing.duplicated().sum())

print(inventory.duplicated().sum())

print(inventory_new.duplicated().sum())

print(delivery.duplicated().sum())

0
0
0
0
0
0
0
7359
0

In [36]:
inventory_new = inventory_new.drop_duplicates()

In [37]:
inventory_new.duplicated().sum()

np.int64(0)

In [38]:
delivery.isnull().sum()

order_id                    0
delivery_partner_id         0
promised_time               0
actual_time                 0
delivery_time_minutes       0
distance_km                 0
delivery_status             0
reasons_if_delayed       1902
dtype: int64

In [39]:
delivery = delivery.fillna(delivery.median(numeric_only=True))

In [40]:
delivery = delivery.fillna("Unknown")

In [41]:
delivery.isnull().sum()

order_id                 0
delivery_partner_id      0
promised_time            0
actual_time              0
delivery_time_minutes    0
distance_km              0
delivery_status          0
reasons_if_delayed       0
dtype: int64

In [42]:
products.dtypes

orders.dtypes

order_items.dtypes

customers.dtypes

feedback.dtypes

marketing.dtypes

inventory.dtypes

inventory_new.dtypes

delivery.dtypes

order_id                   int64
delivery_partner_id        int64
promised_time                str
actual_time                  str
delivery_time_minutes    float64
distance_km              float64
delivery_status              str
reasons_if_delayed           str
dtype: object

In [43]:
products.describe(include="all")

,product_id,product_name,category,brand,price,mrp,margin_percentage,shelf_life_days,min_stock_level,max_stock_level
count,268.000000,268,268,268,268.000000,268.000000,268.000000,268.000000,268.000000,268.000000
unique,NaN,51,11,267,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,Pet Treats,Dairy & Breakfast,Jha Group,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,12,30,2,NaN,NaN,NaN,NaN,NaN,NaN
mean,514855.940299,NaN,NaN,NaN,488.356828,680.434739,27.779851,231.757463,20.388060,74.753731
std,291391.529820,NaN,NaN,NaN,298.487200,419.772224,7.458753,151.205830,5.958546,14.591535
min,4452.000000,NaN,NaN,NaN,12.320000,17.600000,15.000000,3.000000,10.000000,50.000000
25%,273697.750000,NaN,NaN,NaN,226.717500,325.150000,20.000000,90.000000,15.000000,63.750000
50%,541459.000000,NaN,NaN,NaN,442.185000,616.970000,30.000000,365.000000,21.000000,73.000000
75%,754334.000000,NaN,NaN,NaN,779.445000,1056.620000,35.000000,365.000000,25.250000,88.000000
max,993331.000000,NaN,NaN,NaN,995.980000,1633.320000,40.000000,365.000000,30.000000,100.000000

In [44]:
orders.describe(include="all")

,order_id,customer_id,order_date,promised_delivery_time,actual_delivery_time,delivery_status,order_total,payment_method,delivery_partner_id,store_id
count,5.000000e+03,5.000000e+03,5000,5000,5000,5000,5000.00000,5000,5000.000000,5000.000000
unique,NaN,NaN,5000,4999,5000,3,NaN,4,NaN,NaN
top,NaN,NaN,2024-07-17 08:34:01,2024-10-13 14:06:50,2024-07-17 08:47:01,On Time,NaN,Card,NaN,NaN
freq,NaN,NaN,1,2,1,3470,NaN,1285,NaN,NaN
mean,5.029129e+09,5.009685e+07,NaN,NaN,NaN,NaN,2201.86170,NaN,50050.318200,4999.689000
std,2.863533e+09,2.919082e+07,NaN,NaN,NaN,NaN,1303.02438,NaN,28802.276922,2886.089242
min,6.046500e+04,3.181300e+04,NaN,NaN,NaN,NaN,13.25000,NaN,43.000000,1.000000
25%,2.531421e+09,2.404314e+07,NaN,NaN,NaN,NaN,1086.21500,NaN,24928.500000,2509.250000
50%,5.074378e+09,4.997808e+07,NaN,NaN,NaN,NaN,2100.69000,NaN,50262.500000,4987.000000
75%,7.488579e+09,7.621215e+07,NaN,NaN,NaN,NaN,3156.88250,NaN,74478.250000,7500.750000
max,9.998298e+09,9.989390e+07,NaN,NaN,NaN,NaN,6721.46000,NaN,99968.000000,9995.000000

In [45]:
products.nunique()
orders.nunique()
customers.nunique()

customer_id          2500
customer_name        2491
email                2496
phone                2500
address              2500
area                  316
pincode              2494
registration_date     589
customer_segment        4
total_orders           20
avg_order_value      2487
dtype: int64

In [46]:
orders.describe()

,order_id,customer_id,order_total,delivery_partner_id,store_id
count,5.000000e+03,5.000000e+03,5000.00000,5000.000000,5000.000000
mean,5.029129e+09,5.009685e+07,2201.86170,50050.318200,4999.689000
std,2.863533e+09,2.919082e+07,1303.02438,28802.276922,2886.089242
min,6.046500e+04,3.181300e+04,13.25000,43.000000,1.000000
25%,2.531421e+09,2.404314e+07,1086.21500,24928.500000,2509.250000
50%,5.074378e+09,4.997808e+07,2100.69000,50262.500000,4987.000000
75%,7.488579e+09,7.621215e+07,3156.88250,74478.250000,7500.750000
max,9.998298e+09,9.989390e+07,6721.46000,99968.000000,9995.000000

In [47]:
orders.select_dtypes(include="number").corr()

,order_id,customer_id,order_total,delivery_partner_id,store_id
order_id,1.000000,-0.008466,-0.008168,0.006545,-0.007966
customer_id,-0.008466,1.000000,0.034951,-0.020232,0.002190
order_total,-0.008168,0.034951,1.000000,-0.003443,-0.023544
delivery_partner_id,0.006545,-0.020232,-0.003443,1.000000,0.007138
store_id,-0.007966,0.002190,-0.023544,0.007138,1.000000

In [49]:
products["category"].value_counts()

category
Dairy & Breakfast        30
Fruits & Vegetables      27
Snacks & Munchies        27
Household Care           27
Personal Care            25
Pet Care                 25
Pharmacy                 25
Grocery & Staples        24
Cold Drinks & Juices     22
Instant & Frozen Food    20
Baby Care                16
Name: count, dtype: int64

In [56]:
customers.columns

Index(['customer_id', 'customer_name', 'email', 'phone', 'address', 'area',
       'pincode', 'registration_date', 'customer_segment', 'total_orders',
       'avg_order_value'],
      dtype='str')

In [57]:
print(customers.columns.tolist())

['customer_id', 'customer_name', 'email', 'phone', 'address', 'area', 'pincode', 'registration_date', 'customer_segment', 'total_orders', 'avg_order_value']

In [58]:
customers["area"].value_counts().head(10)

area
Jalna          18
Orai           17
Bathinda       17
Deoghar        17
Ratlam         16
Ghaziabad      16
Kishanganj     15
Nandyal        14
Kadapa         14
Gandhinagar    14
Name: count, dtype: int64

In [59]:
customers["customer_segment"].value_counts()

customer_segment
Regular     639
Premium     633
New         628
Inactive    600
Name: count, dtype: int64

In [60]:
customers["avg_order_value"].describe()

count    2500.000000
mean     1102.375836
std       523.043183
min       200.430000
25%       631.817500
50%      1118.650000
75%      1565.400000
max      1999.830000
Name: avg_order_value, dtype: float64

In [61]:
customers["total_orders"].describe()

count    2500.000000
mean       10.491600
std         5.805533
min         1.000000
25%         6.000000
50%        10.000000
75%        16.000000
max        20.000000
Name: total_orders, dtype: float64

In [62]:
products.head()
products.columns.tolist()

['product_id',
 'product_name',
 'category',
 'brand',
 'price',
 'mrp',
 'margin_percentage',
 'shelf_life_days',
 'min_stock_level',
 'max_stock_level']

In [63]:
orders.columns.tolist()
orders.head()

,order_id,customer_id,order_date,promised_delivery_time,actual_delivery_time,delivery_status,order_total,payment_method,delivery_partner_id,store_id
0,1961864118,30065862,2024-07-17 08:34:01,2024-07-17 08:52:01,2024-07-17 08:47:01,On Time,3197.07,Cash,63230,4771
1,1549769649,9573071,2024-05-28 13:14:29,2024-05-28 13:25:29,2024-05-28 13:27:29,On Time,976.55,Cash,14983,7534
2,9185164487,45477575,2024-09-23 13:07:12,2024-09-23 13:25:12,2024-09-23 13:29:12,On Time,839.05,UPI,39859,9886
3,9644738826,88067569,2023-11-24 16:16:56,2023-11-24 16:34:56,2023-11-24 16:33:56,On Time,440.23,Card,61497,7917
4,5427684290,83298567,2023-11-20 05:00:39,2023-11-20 05:17:39,2023-11-20 05:18:39,On Time,2526.68,Cash,84315,2741

In [64]:
products.to_csv("products_clean.csv", index=False)
orders.to_csv("orders_clean.csv", index=False)
order_items.to_csv("order_items_clean.csv", index=False)
customers.to_csv("customers_clean.csv", index=False)
feedback.to_csv("feedback_clean.csv", index=False)
marketing.to_csv("marketing_clean.csv", index=False)
inventory.to_csv("inventory_clean.csv", index=False)
inventory_new.to_csv("inventoryNew_clean.csv", index=False)
delivery.to_csv("delivery_clean.csv", index=False)

In [65]:
[f for f in os.listdir() if "clean" in f.lower()]

['Amazon_Cleaned.csv',
 'Amazon_Cleaned.xlsx',
 'Amazon_Cleaned_1.csv',
 'Amazon_data_cleaning.ipynb',
 'Blinkit_Cleaned.ipynb',
 'customers_clean.csv',
 'delivery_clean.csv',
 'feedback_clean.csv',
 'HR_Analytics_Cleaned.csv',
 'inventoryNew_clean.csv',
 'inventory_clean.csv',
 'marketing_clean.csv',
 'orders_clean.csv',
 'order_items_clean.csv',
 'products_clean.csv']